let AllMusic = [
    {
        name: "Мукка - Девочка с Каре",
        image: "img/GirlWithKare.jpg",
        path: "sounds/GirlWithKare.mp3"
    },
    {
        name: "Harvey Myers - N-word Areas",
        image: "img/Niggers.jpg",
        path: "sounds/Niggers.mp3"
    },
    {
        name: "UwU Phonky",
        image: "img/UwU.jpg",
        path: "sounds/UwUPhonky.mp3"
    },
    {
        name: "BLOODYSHADOW",
        image: "img/BloodyShadow.jpg",
        path: "sounds/BLOODYSHADOW.mp3"
    }
]
